### ISSUE TITLE
ComicStreamer Admin permissions

### ISSUE THREAD

**Issue by AngryNoodlez** [hjone72/PlexAuth#12]
Hey,

I'm not sure if this has been covered elsewhere, but couldn't find anything on the issues tracker.

I've managed to get the ComicStreamer SSO working with PlexAuth, but since doing so I'm unable to access any of the settings pages for ComicStreamer.

Is there a method for either the owner of the Plex server to be assigned these rights, or an alternate login option for managing these?

Thanks!

**Comment by hjone72** [comment]
For my instance I simply removed the end points and edit the settings manually.

If you still wanted to be able to access those settings it would probably make sense to add another auth point in your nginx config.

**Comment by AngryNoodlez** [comment]
Thanks for this!

I ended up going with Ubooquity and setting it to use local browser storage. The interface is nice! Though the search and index features aren't anything like what's available in ComicStreamer.

As a side note before I close this, and please let me know if you want me to open this in a seperate issue;

Do you happen to have any guidance on how you got Bumpy Booby working with SSO? I've downloaded your fork but I don't quite understand the process of how SSO works with this webapp. Unlike ComicStreamer or PlexPy where they have modules and the apps authenticate with the PlexAuth URL, this appears to use a different method for auth. No matter what I've tried so far, I just keep hitting the redirect back to PlexAuth URL.

**Comment by hjone72** [comment]
BumpyBooby was a bit of a rushed implementation. I've never had an issue with it working though so never came back and fixed it up. Unfortunately there isn't a config file to update settings etc so you'll need to make the changes in place.

Have a read through these two pages and update them with your values:
https://github.com/hjone72/Bumpy-Booby/blob/master/pages/signup.php (Line 6, 7, 12, 13, 32, maybe more)
https://github.com/hjone72/Bumpy-Booby/blob/master/index.php (Line 225 - 302)

BumbyBooby is a very simple issue tracker, which is why I like it. I had forgotten at how rushed it was, it could really use a clean up on how it works. Post back if you're still having trouble. And if you don't mind keeping some notes as you go through we could use that to help anyone else.

If you're happy to settle for Same Sign-On, you could make use of https://github.com/hjone72/LDAP-for-Plex and use any issue tracker that supports LDAP. Just an idea 😄

**Comment by AngryNoodlez** [comment]
So I'm pretty sure I kept my values default (ytbuser) as I can see this referenced in the RememberMe.php file.

I host everything behind a single subdomain "https://portal.domain.com", so the only changes I've made are to these lines;

[Signup.php Line 32](https://github.com/hjone72/Bumpy-Booby/blob/5636c68f7517b9dfd7c6ff8c8c7adeb8053c6cf7/pages/signup.php#L32)

    header("Location: https://portal.domain.com"); //Change this to URL of PlexAuth



[Index.php Lines 298-299](https://github.com/hjone72/Bumpy-Booby/blob/5636c68f7517b9dfd7c6ff8c8c7adeb8053c6cf7/index.php#L298-L299)

    $_SESSION['return_url'] = "https://portal.domain.com/support"; //URL of this site.
    header("Location: https://portal.domain.com"); //URL of PlexAuth.


It seems to just always redirect me to the URL specified on [L299](https://github.com/hjone72/Bumpy-Booby/blob/5636c68f7517b9dfd7c6ff8c8c7adeb8053c6cf7/index.php#L298-L299) so I'm not sure what that means!

I'll make sure to note down any changes to keep track, I have a habbit of doing it anyway! And that PlexAuth LDAP looks awesome! I'm sure I can find many uses for that.

Thanks again

**Comment by hjone72** [comment]
If you've got time jump onto this discord and I'll see if we can figure it out.

**Comment by AngryNoodlez** [comment]
Hey, I saw your reply in Discord but then got disconnected from the channel. I just get "1 server is unavailable due to a temporary outage".

Any ideas?

**Comment by hjone72** [comment]
They aren't normally down for very long. Give it 5 minutes. Or have you got
a different IRC you'd prefer?

**Comment by AngryNoodlez** [comment]
I don't really use any other IRCs, we can wait if it's not normally down long - or if you have any others?

**Comment by AngryNoodlez** [comment]
Closing as you kindly got this issue resolved for me! 👍🏻
