### ISSUE TITLE
Feature Request: Seperate plex auth module for nginx 

### ISSUE THREAD

**Issue by ajkis** [hjone72/PlexAuth#17]
Any chance you could release plex auth just for nginx module so we could implement it for any custom page.

Example: I have simple readme.php page that I would like to go trough plex auth.

**Comment by hjone72** [comment]
All the nginx module requires is a page that responds with either a 200 or any other code. If it receives a 200 it allows the request through to the protected page. Otherwise deny.

If you're only trying to protect 1 page you may be better looking at a more nginx pure solution, where the credential checking is handled by nginx too. No matter what, a solution similar to this one will require a fair bit of overhead to protect 1 page.

That being said, if you don't care about that you could simply replace the index page from PlexAuth with your readme.php and it'd work out of the box.

Enjoy :)

**Comment by ajkis** [comment]
Any idea how to do pure nginx solution with one page.

**Comment by hjone72** [comment]
I've never tested or used this but: https://github.com/mstinaff/PlexAuth

**Comment by ajkis** [comment]
Tried it and it seems its not working anymore.

**Comment by hjone72** [comment]
If it is a php page you're trying to protect why don't you write some auth into the page directly?

**Comment by ajkis** [comment]
I wanted it to go trough plex auth so users dont need special user/pass for it.

**Comment by hjone72** [comment]
Have a look here: https://github.com/hjone72/PlexAuth/blob/master/inc/PlexUser.class.php#L37

All you'd need to do is present the user a login form (username + password) then enter them into a function similar to this one. If a token is returned they are authed.

If you want to check if you have shared your plex with them make use of this function: https://github.com/hjone72/PlexAuth/blob/master/inc/PlexUser.class.php#L178

What you're trying to do is very do-able.

Question, why not take the next step and run everything behind PlexAuth or Organizr?

**Comment by ajkis** [comment]
Thanks for suggestions, I solved it.
