### ISSUE TITLE
Trouble since the introduction of the "RememberMe by gbirke" requirement

### ISSUE THREAD

**Issue by metroplexing** [hjone72/PlexAuth#2]
First off great job on this solution (quite worthy on it's own post on r/Plex and on the General (Third-Party Development) for the Plex forum. I've been tracking this project since you initially mentioned it on a Reddit thread for "Working on another Web Portal Manager". You gave me some initial pointers for setting it up, so thanks for including your nginx example.

Few questions:
-Does the RememberMe install have to be in the same directory as PlexAuth (I keep getting errors)?
-Can I tie your solution to Muximux (for authentication) replacing mainpage.php (in the INC folder) on the launch?
-Regarding Nginx, can your solution sit all on the same server block or does that have to be separated out (like you did in the example)?

Seems the trend are Plex users building out or finding additional offerings (PlexRequests, PlexPy (guest mode),PlexLanding, Ubooquity etc.) and then bundling them all via iFrame based offerings (Muximux/ManageThis/ManageThisNode) for folks they are sharing with (all tied under Ngninx/Apache setups with SSL/TLS). The missing piece (under Apache/Nginx) is the current way authentication is handled, which is where your solution comes in. Sure most have stated they are getting by with the "auth_basic" approach and not "auth_request" for inbound requests to their respective dashboards but PlexAuth seems to be the way forward (the Plex forum is also hopeful two factor is delivered in 2016). Hopefully with your latest update once folks log in through PlexAuth (when I get it working), the token passed will unlock and log users into the PlexPy, PlexRequests, and PlexTV ("IPaddress:32400/web" since use of plex.tv/app isn't allowed to be run within an iFrame) created tabs on Muximux (with their own PLEX account names).

The only suggestion I would make, is to utilize Plex colors on the login (even though we can do it ourselves).

Thanks for your time.

**Comment by hjone72** [comment]
Thanks for the feedback. I wanted it to be a bit more complete before advertising it too much.
1. RememberMe can be installed anywhere, just remember change the reference to the "autoload.php" [See Here](https://github.com/hjone72/PlexAuth/blob/master/inc/RememberMe.php#L4). In my usage I have RememberMe installed under "inc". So my directory structure looks like; /var/www/html/PlexAuth/inc/rememberme/*
2. I haven't looked too much at Muximux but I don't see a reason why that wouldn't work.
3. Yeah you can have it under one server block but you would need to only auth the individual locations not the entire server block otherwise you wouldn't be able to access the auth page.

You detailed my idea/plan pretty well. I hate the idea of shared usernames and passwords. I wanted some way to allow people to use credentials they already have, know and use. I stumbled across the auth_request module for nginx and started work on this. My end goal is to have the main page showing status to services, rss feed of updates/issues [Using a modified version of this](https://github.com/piero-la-lune/Bumpy-Booby), etc

I hadn't thought of trying to auto login to Plex as well... I will look and see if I can figure out how that works and I'll try and include it.

I'm not very good with CSS, I had a friend of mine make up the design of the page. If you are able to Plex Theme it please do so!

Hope this answers your questions, let me know if you need further assistance.

**Comment by Shmee** [comment]
> Regarding Nginx, can your solution sit all on the same server block or does that have to be separated out (like you did in the example)?

I was able to reverse proxy plex under the same domain name with no port. it looks like I can write javascript to auto login to plex by writing to localstorage. I'm looking into that now.

so I can login and watch stuff under my main domain

> domain.com/web/index.html

```
   location ^~ /web/ {
                if ($http_x_plex_device_name = '') {
                                rewrite ^/$ http://$http_host/web/index.html;
                }
                # set some headers and proxy stuff.
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                # include Host header
                proxy_set_header Host $http_host;

                # proxy request to plex server
                proxy_pass http://192.168.1.10:32400;

                proxy_redirect off;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 36000s;
    }
```

So I have plexauth login at

> domain.com/index.php

plexrequests reverse proxied

> domain.com/requests

plexpy reverse proxied at

> domain.com/stats

sonarr

> domain.com/sonarr

couchpotato

> domain.com/couchepotato

utorrent

> domain.com/utorrent
